//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Restaurante.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_Restaurante.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap actualizar__1_ {
            get {
                object obj = ResourceManager.GetObject("actualizar (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap electricity_bill {
            get {
                object obj = ResourceManager.GetObject("electricity-bill", resourceCulture);
>>>>>>> e25f8827094f88b6493b8c7add722f121c934896
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap disquete {
            get {
                object obj = ResourceManager.GetObject("disquete", resourceCulture);
=======
        internal static System.Drawing.Bitmap food_delivery {
            get {
                object obj = ResourceManager.GetObject("food-delivery", resourceCulture);
>>>>>>> e25f8827094f88b6493b8c7add722f121c934896
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap lupa__1_ {
            get {
                object obj = ResourceManager.GetObject("lupa (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap plates {
            get {
                object obj = ResourceManager.GetObject("plates", resourceCulture);
>>>>>>> e25f8827094f88b6493b8c7add722f121c934896
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap registro {
            get {
                object obj = ResourceManager.GetObject("registro", resourceCulture);
=======
        internal static System.Drawing.Bitmap plates1 {
            get {
                object obj = ResourceManager.GetObject("plates1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restaurant {
            get {
                object obj = ResourceManager.GetObject("restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restaurant1 {
            get {
                object obj = ResourceManager.GetObject("restaurant1", resourceCulture);
>>>>>>> e25f8827094f88b6493b8c7add722f121c934896
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
